version: "3"
services:
    #Gateway
    gateway:
        build:
            context: ./gateway
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - character
        networks:
            - starwars-network
    # Components services
    character:
        build:
            context: ./character
            dockerfile: Dockerfile
        ports:
            - "8001:8001"
        depends_on:
            - film
        networks:
            - starwars-network
    film:
        build:
            context: ./film
            dockerfile: Dockerfile
        ports:
            - "8002:8002"
        depends_on:
            - planet
        networks:
            - starwars-network
    planet:
        build:
            context: ./planet
            dockerfile: Dockerfile
        ports:
            - "8003:8003"
        depends_on:
            - store
        networks:
            - starwars-network
    # Store service
    store:
        build:
            context: ./planets
            dockerfile: Dockerfile
        ports:
            - "8004:8004"
        networks:
            - starwars-network
    # Mongo service

networks:
    starwars-network:
